# -*- coding: utf-8 -*-
"""mis_funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NAn7xRY56vIr27RB-j_FefkdXuGmu93H
"""

def plotimagenes_curvaroc(path, columna_analisis):
  import matplotlib.pyplot as plt
  import cv2
  import os

  # Carpeta donde están los archivos
  output_dir = path

  # Rango de repeticiones y folds
  num_reps = 6
  num_folds = 5

  for columna in columna_analisis:
      for rep in range(num_reps):
          for fold in range(num_folds):
              filename = f"curva_roc_{columna}_rep{rep+1}_fold{fold+1}.png"
              filepath = os.path.join(output_dir, filename)

              img = cv2.imread(filepath)
              if img is None:
                  print(f"No se encontró {filename}")
                  continue

              img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

              plt.figure(figsize=(30,30))
              plt.imshow(img_rgb)
              plt.title(f"{columna} | Rep {rep+1} | Fold {fold+1}")
              plt.axis("off")
              plt.show()

def plotimagenes_tsnereal(path, columna_analisis):
  import matplotlib.pyplot as plt
  import cv2
  import os

  # Carpeta donde están los archivos
  output_dir = path

  # Rango de repeticiones y folds
  num_reps = 6
  num_folds = 5

  for columna in columna_analisis:
      for rep in range(num_reps):
          for fold in range(num_folds):
              filename = f"tsne_real_{columna}_rep{rep+1}_fold{fold+1}.png"
              filepath = os.path.join(output_dir, filename)

              img = cv2.imread(filepath)
              if img is None:
                  print(f"No se encontró {filename}")
                  continue

              img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

              plt.figure(figsize=(30,30))
              plt.imshow(img_rgb)
              plt.title(f"{columna} | Rep {rep+1} | Fold {fold+1}")
              plt.axis("off")
              plt.show()

def plotimagenes_tsnepred(path, columna_analisis):
  import matplotlib.pyplot as plt
  import cv2
  import os

  # Carpeta donde están los archivos
  output_dir = path

  # Rango de repeticiones y folds
  num_reps = 6
  num_folds = 5
  for columna in columna_analisis:
    for rep in range(num_reps):
      for fold in range(num_folds):
        filename = f"tsne_predicho_{columna}_rep{rep+1}_fold{fold+1}.png"
        filepath = os.path.join(output_dir, filename)
        img = cv2.imread(filepath)
        if img is None:
          print(f"No se encontró {filename}")
          continue

        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        plt.figure(figsize=(30,30))
        plt.imshow(img_rgb)
        plt.title(f"{columna} | Rep {rep+1} | Fold {fold+1}")
        plt.axis("off")
        plt.show()

def grafentrena(jajaxd, columna_analisis, rep, fold, output_dir='.'):
      'se pone el historial nadamas xd'
      plt.figure(figsize=(12,5))

      plt.plot(jajaxd["accuracy"], label="Precisión", color="green", linewidth=1.5)
      plt.plot(jajaxd["loss"], label="Pérdida", color="black", linewidth=1.5)

      plt.xlabel("Épocas")
      plt.ylabel("Valor")
      plt.title(f"Entrenamiento de {columna_analisis} - Rep {rep+1}, Fold {fold+1}\n")
      plt.legend()
      plt.grid(True)
      plt.ylim(0,1)
      plt.tight_layout()
      plt.savefig(f"{output_dir}/entrenamiento_{columna_analisis}_rep{rep+1}_fold{fold+1}.png")
      plt.close() # Close the plot to free up memory

def grafprecval(jajaxd2, columna_analisis2, rep, fold, output_dir='.'):
      'se pone el historial nadamas xd'
      # Accuracy
      plt.figure(figsize=(12,5))
      plt.plot(jajaxd2["accuracy"], label="Train Accuracy", color="green", linewidth=1.5)
      plt.plot(jajaxd2["val_accuracy"], label="Validation Accuracy", color="black", linewidth=1.5)
      plt.xlabel("Épocas")
      plt.ylabel("Precisión")
      plt.title(f"Precisión entrenamiento vs validación de {columna_analisis2} - Rep {rep+1}, Fold {fold+1}\n")
      plt.legend()
      plt.grid(True)
      plt.ylim(0,1)
      plt.tight_layout()
      plt.savefig(f"{output_dir}/precision_entrenamiento_validacion_{columna_analisis2}_rep{rep+1}_fold{fold+1}.png")
      plt.close() # Close the plot to free up memory

def grafperval(jajaxd3, columna_analisis3, rep, fold, output_dir='.'):
  'se pone el historial nadamas xd'
  plt.figure(figsize=(12,5))
      # Loss
  plt.plot(jajaxd3["loss"], label="Train Loss", color="green", linewidth=1.5)
  plt.plot(jajaxd3["val_loss"], label="Validation Loss", color="black", linewidth=1.5)
  plt.xlabel("Épocas")
  plt.ylabel("Pérdida")
  plt.title(f"Pérdida entrenamiento vs validación de {columna_analisis3} - Rep {rep+1}, Fold {fold+1}\n")
  plt.legend()
  plt.grid(True)
  plt.ylim(0,1)
  plt.tight_layout()
  plt.savefig(f"{output_dir}/perdida_entrenamiento_validacion_{columna_analisis3}_rep{rep+1}_fold{fold+1}.png")
  plt.close() # Close the plot to free up memory

def metodo_tsne(archivo, columna_analizar, columna_color, rep, fold, output_dir='.'):
    """
    Genera visualización t-SNE y exporta tanto en HTML interactivo como en PNG con estilo Plotly.
    """
    import numpy as np
    import plotly.express as px
    from sklearn.manifold import TSNE

    # Configuración de reproducibilidad
    np.random.seed(42)

    # Ajustar t-SNE (limitando a 100 filas como en tu versión original)
    tsne = TSNE(perplexity=20, early_exaggeration=50, learning_rate=350, random_state=42)
    X_valid_2D = tsne.fit_transform(archivo[0:100])

    # Normalización de valores a escala [0, 1]
    X_valid_2D = (X_valid_2D - X_valid_2D.min()) / (X_valid_2D.max() - X_valid_2D.min())

    # Crear gráfico interactivo con Plotly
    fig = px.scatter(
        x=X_valid_2D[:, 0],
        y=X_valid_2D[:, 1],
        color=columna_analizar.astype(str),
        title=f"Visualización del conjunto de datos reales de {columna_color}\n- Rep {rep+1}, Fold {fold+1}"
    )

    fig.update_traces(marker=dict(size=10, opacity=0.7, line=dict(width=2)))
    fig.update_layout(showlegend=True)

    # Guardar en HTML interactivo
    fig.write_html(f"{output_dir}/tsne_real_{columna_color}_rep{rep+1}_fold{fold+1}.html")

    # Guardar en PNG con estilo Plotly (requiere kaleido)
    fig.write_image(
        f"{output_dir}/tsne_real_{columna_color}_rep{rep+1}_fold{fold+1}.png",
        width=1200, height=800, scale=2  # puedes ajustar tamaño y resolución
    )

def metodo_tsne2(archivo, columna_analizar, columna_color, rep, fold, output_dir='.'):
    """
    Genera un gráfico t-SNE y lo guarda en formato PNG con estilo Plotly.
    """
    import numpy as np
    import plotly.express as px
    from sklearn.manifold import TSNE

    # Configuración
    np.random.seed(42)
    tsne = TSNE(perplexity=20, early_exaggeration=50, learning_rate=350, random_state=42)
    X_valid_2D = tsne.fit_transform(archivo[0:100])

    # Normalización de valores de escala 0 a 1
    X_valid_2D = (X_valid_2D - X_valid_2D.min()) / (X_valid_2D.max() - X_valid_2D.min())

    # Crear gráfico con Plotly
    fig = px.scatter(
        x=X_valid_2D[:, 0],
        y=X_valid_2D[:, 1],
        color=columna_analizar.astype(str),
        title=f"Visualización del conjunto de datos predichos de {columna_color}\n- Rep {rep+1}, Fold {fold+1}"
    )

    # Configurar apariencia
    fig.update_traces(marker=dict(size=10, opacity=0.7, line=dict(width=2)))
    fig.update_layout(showlegend=True)

    # Guardar en PNG con estilo Plotly
    fig.write_image(
        f"{output_dir}/tsne_predicho_{columna_color}_rep{rep+1}_fold{fold+1}.png",
        width=1200, height=800, scale=2  # tamaño y resolución ajustables
    )

def redes_neuronales(x,y):
  'X es la entrada de valores que quieres usar como referencia para predecir los valores y, necesitan estar definidas las columnas por pandas'
  import tensorflow
  from tensorflow import keras
  from tensorflow.keras import layers
  import pandas as pd
  import numpy as np
  import matplotlib.pyplot as plt
  from sklearn.model_selection import train_test_split
  from sklearn.preprocessing import StandardScaler
  from tensorflow.keras import regularizers
  from tensorflow.keras.callbacks import EarlyStopping
  x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.45, random_state=42)
  model = keras.Sequential([layers.Dense(512, activation="relu"),
                              layers.Dense(100, activation="relu"),
                              layers.Dense(100, activation="relu"),
                              layers.Dense(100, activation="relu"),
                              layers.Dense(1, activation="sigmoid")])
  model.compile(optimizer="rmsprop",
                  loss="binary_crossentropy",
                  metrics=["accuracy"])

  history = model.fit(x_train, y_train, epochs=500, batch_size=100)
  model.summary()
  hist_df = pd.DataFrame(history.history)

  plt.figure(figsize=(7,5))

  plt.plot(hist_df["accuracy"], label="Precisión", color="green", linewidth=0.9)
  plt.plot(hist_df["loss"], label="Pérdida", color="black", linewidth=0.9)

  plt.xlabel("Épocas")
  plt.ylabel("Valor")
  plt.title("Entrenamiento\n")
  plt.legend()
  plt.grid(True)
  plt.ylim(0,1)
  plt.show()
  model.evaluate(x_test,y_test)

def confusion_matrixo(y_real, y_pred, otro_titulo, rep, fold, output_dir='.'):
    import seaborn as sns
    import matplotlib.pyplot as plt
    import numpy as np
    from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

    # Calcular matriz
    matriz = confusion_matrix(y_real, y_pred)
    print(matriz)

    # Calcular métricas
    acc = accuracy_score(y_real, y_pred)
    prec = precision_score(y_real, y_pred, zero_division=0)
    rec = recall_score(y_real, y_pred, zero_division=0)
    f1 = f1_score(y_real, y_pred, zero_division=0)

    # Normalizar matriz para colores
    matriz_norm = matriz.astype('float') / matriz.sum(axis=1)[:, np.newaxis]

    # Crear figura
    plt.figure(figsize=(6, 5))
    sns.heatmap(matriz_norm, annot=matriz, fmt="d", cmap="Greens",
                xticklabels=["Pred:0", "Pred:1"],
                yticklabels=["Real:0", "Real:1"],
                cbar_kws={'label': 'Proporción'})

    plt.ylabel("Valor Real")
    plt.xlabel("Predicción")

    # Título con métricas
    plt.title(f"{otro_titulo} - Rep {rep+1}, Fold {fold+1}\n")

    # Guardar archivo
    plt.savefig(f"{output_dir}/matriz_confusion_{otro_titulo}_rep{rep+1}_fold{fold+1}.png")
    plt.close()

def curva_roc(y_true, y_predo, titulo, rep, fold, output_dir='.'):
  'En este metodo se hace la curva roc de dos valores, y_true y y_pred los cuales, y_true, y titulo es la columna a analizar'
  import matplotlib.pyplot as plt
  from sklearn.metrics import roc_curve, roc_auc_score
  # Calcular FPR, TPR y thresholds
  fpr, tpr, thresholds = roc_curve(y_true, y_predo)

  # Calcular AUC
  auc = roc_auc_score(y_true, y_predo)

  # Graficar curva ROC
  plt.figure(figsize=(6, 5)) # Added figure size for consistency
  plt.plot(fpr, tpr, label=f"AUC = {auc:.2f}", color="green")
  plt.plot([0, 1], [0, 1], linestyle="--", color="gray")  # línea aleatoria
  plt.xlabel("Tasa de Falsos Positivos (FPR)")
  plt.ylabel("Tasa de Verdaderos Positivos (TPR)")
  plt.title(f"Curva ROC de {titulo} - Rep {rep+1}, Fold {fold+1}\n")
  plt.legend()
  plt.savefig(f"{output_dir}/curva_roc_{titulo}_rep{rep+1}_fold{fold+1}.png")
  plt.close() # Close the plot to free up memory

def porc_comparacion(y_realote, y_predicho):
  comparacion = [a == b for a, b in zip(y_realote, y_predicho)]
  # Calcular similitud
  similitud = sum(comparacion) / len(comparacion) * 100

  print("Comparación:", comparacion)
  print(f"Similitud: {similitud:.2f}%")